export const PRODUCERS = [
	{ label: 'A. Morin', value: 'a. morin' }, 
    { label: 'Amedei', value: 'amedei' }, 
    { label: 'Arete', value: 'arete' }, 
    { label: 'Bellflower', value: 'bellflower' }, 
    { label: 'Benoit Nihant', value: 'benoit nihant' }, 
    { label: 'Blanxart', value: 'blanxart' }, 
    { label: 'Burnt Fork Bend', value: 'burnt fork bend' }, 
    { label: 'Cacao Sampaka', value: 'cacao sampaka' }, 
    { label: 'Cacaosuyo (Theobroma Inversiones)', value: 'cacaosuyo (theobroma inversiones)' }, 
    { label: 'Cacaoyere (Ecuatoriana)', value: 'cacaoyere (ecuatoriana)' }, 
    { label: 'Compania de Chocolate (Salgado)', value: 'compania de chocolate (salgado)' }, 
    { label: 'Duffys', value: 'duffys' }, 
    { label: 'El Rey', value: 'el rey' }, 
    { label: 'Ethels Artisan (Mars)', value: 'ethels artisan (mars)' },
    { label: 'Fresco', value: 'fresco' }, 
    { label: 'Fruition', value: 'fruition' }, 
    { label: 'Habitual', value: 'habitual' }, 
    { label: 'Hotel Chocolat (Coppeneur)', value: 'hotel chocolat (coppeneur)' }, 
    { label: 'Hummingbird', value: 'hummingbird' }, 
    { label: 'Idilio (Felchlin)', value: 'idilio (felchlin)' }, 
    { label: 'K ul', value: 'k ul' }, 
    { label: 'L.A. Burdick (Felchlin)', value: 'l.a. burdick (felchlin)' }, 
    { label: 'Letterpress', value: 'letterpress' }, 
    { label: 'Lillie Belle', value: 'lillie belle' }, 
    { label: 'Manufaktura Czekolady', value: 'manufaktura czekolady' }, 
    { label: 'Matale', value: 'matale' }, 
    { label: 'Michel Cluizel', value: 'michel cluizel' }, 
    { label: 'Monarque', value: 'monarque' }, 
    { label: 'Montecristi', value: 'montecristi' }, 
    { label: 'Ocelot', value: 'ocelot' }, 
    { label: 'Omnom', value: 'omnom' }, 
    { label: 'Pacari', value: 'pacari' }, 
    { label: 'Paul Young', value: 'paul young' }, 
    { label: 'Pralus', value: 'pralus' }, 
    { label: 'Q Chocolate', value: 'q chocolate' }, 
    { label: 'Republica del Cacao (aka Confecta)', value: 'republica del cacao (aka confecta)' }, 
    { label: 'Scharffen Berger', value: 'scharffen berger' }, 
    { label: 'Sirene', value: 'sirene' }, 
    { label: 'Smooth Chocolator, The', value: 'smooth chocolator, the' }, 
    { label: 'StRita Supreme', value: 'strita supreme' }, 
    { label: 'Tabal', value: 'tabal' }, 
    { label: 'Tejas', value: 'tejas' }, 
    { label: 'Valrhona', value: 'valrhona' }, 
    { label: 'Vao Vao (Chocolaterie Robert)', value: 'vao vao (chocolaterie robert)' }, 
    { label: 'Woodblock', value: 'woodblock' }, 
    { label: 'Adi', value: 'adi' }, 
    { label: 'Aequare (Gianduja)', value: 'aequare (gianduja)' }, 
    { label: 'AMMA', value: 'amma' }, 
    { label: 'Artisan du Chocolat', value: 'artisan du chocolat' }, 
    { label: 'Bar Au Chocolat', value: 'bar au chocolat' }, 
    { label: 'Black Mountain', value: 'black mountain' }, 
    { label: 'Bonnat', value: 'bonnat' }, 
    { label: 'Bouga Cacao (Tulicorp)', value: 'bouga cacao (tulicorp)' }, 
    { label: 'Caoni (Tulicorp)', value: 'caoni (tulicorp)' }, 
    { label: 'Captain Pembleton', value: 'captain pembleton' }, 
    { label: 'Castronovo', value: 'castronovo' }, 
    { label: 'Chocola te', value: 'chocola te' }, 
    { label: 'Chocovic', value: 'chocovic' }, 
    { label: 'Dick Taylor', value: 'dick taylor' }, 
    { label: 'Domori', value: 'domori' }, 
    { label: 'Durand', value: 'durand' }, 
    { label: 'El Ceibo', value: 'el ceibo' }, 
    { label: 'Erithaj (A. Morin)', value: 'erithaj (a. morin)' }, 
    { label: 'Finca', value: 'finca' }, 
    { label: 'Friis Holm (Bonnat)', value: 'friis holm (bonnat)' }, 
    { label: 'Guittard', value: 'guittard' }, 
    { label: 'Izard', value: 'izard' }, 
    { label: 'Kakao', value: 'kakao' }, 
    { label: 'Madre', value: 'madre' }, 
    { label: 'Malagos', value: 'malagos' }, 
    { label: 'Mana', value: 'mana' }, 
    { label: 'Marsatta', value: 'marsatta' }, 
    { label: 'Mast Brothers', value: 'mast brothers' }, 
    { label: 'Middlebury', value: 'middlebury' }, 
    { label: 'Oakland Chocolate Co.', value: 'oakland chocolate co.' }, 
    { label: 'Olive and Sinclair', value: 'olive and sinclair' }, 
    { label: 'Olivia', value: 'olivia' }, 
    { label: 'Original Beans (Felchlin)', value: 'original beans (felchlin)' }, 
    { label: 'Pascha', value: 'pascha' }, 
    { label: 'Pierre Marcolini', value: 'pierre marcolini' }, 
    { label: 'Pitch Dark', value: 'pitch dark' }, 
    { label: 'Rogue', value: 'rogue' }, 
    { label: 'S.A.I.D.', value: 's.a.i.d.' }, 
    { label: 'Seaforth', value: 'seaforth' }, 
    { label: 'Snake & Butterfly', value: 'snake & butterfly' }, 
    { label: 'Solomons Gold', value: 'solomons gold' }, 
    { label: 'Soma', value: 'soma' }, 
    { label: 'Starchild', value: 'starchild' }, 
    { label: 'twenty-four blackbirds', value: 'twenty-four blackbirds' }, 
    { label: 'Videri', value: 'videri' }, 
    { label: 'Willies Cacao', value: 'willies cacao' }, 
    { label: 'Zaks', value: 'zaks' }, 
    { label: 'Zotter', value: 'zotter' }, 
    { label: 'Alain Ducasse', value: 'alain ducasse' }, 
    { label: 'Altus aka Cao Artisan', value: 'altus aka cao artisan' }, 
    { label: 'Bakau', value: 'bakau' }, 
    { label: 'Beehive', value: 'beehive' }, 
    { label: 'Belyzium', value: 'belyzium' }, 
    { label: 'Black River (A. Morin)', value: 'black river (a. morin)' }, 
    { label: 'Cacao Atlanta', value: 'cacao atlanta' }, 
    { label: 'Cacao de Origen', value: 'cacao de origen' }, 
    { label: 'Callebaut', value: 'callebaut' }, 
    { label: 'Chchukululu (Tulicorp)', value: 'chchukululu (tulicorp)' }, 
    { label: 'Damson', value: 'damson' }, 
    { label: 'Dandelion', value: 'dandelion' }, 
    { label: 'Danta', value: 'danta' }, 
    { label: 'DeVries', value: 'devries' }, 
    { label: 'Doble & Bignall', value: 'doble & bignall' }, 
    { label: 'East Van Roasters', value: 'east van roasters' }, 
    { label: 'Hachez', value: 'hachez' }, 
    { label: 'hello cocoa', value: 'hello cocoa' }, 
    { label: 'La Maison du Chocolat (Valrhona)', value: 'la maison du chocolat (valrhona)' }, 
    { label: 'Maglio', value: 'maglio' }, 
    { label: 'Manoa', value: 'manoa' }, 
    { label: 'Maverick', value: 'maverick' }, 
    { label: 'Mayacama', value: 'mayacama' }, 
    { label: 'Meadowlands', value: 'meadowlands' }, 
    { label: 'Nahua', value: 'nahua' }, 
    { label: 'Ritual', value: 'ritual' }, 
    { label: 'Roasting Masters', value: 'roasting masters' }, 
    { label: 'Rozsavolgyi', value: 'rozsavolgyi' }, 
    { label: 'Shark Mountain', value: 'shark mountain' }, 
    { label: 'Szanto Tibor', value: 'szanto tibor' }, 
    { label: 'Tablette (aka Vanillabeans)', value: 'tablette (aka vanillabeans)' }, 
    { label: 'TCHO', value: 'tcho' }, 
    { label: 'Terroir', value: 'terroir' }, 
    { label: 'Tobago Estate (Pralus)', value: 'tobago estate (pralus)' }, 
    { label: 'Tocoti', value: 'tocoti' }, 
    { label: 'Ambrosia', value: 'ambrosia' }, 
    { label: 'Animas', value: 'animas' }, 
    { label: 'Beschle (Felchlin)', value: 'beschle (felchlin)' }, 
    { label: 'Cacao Hunters', value: 'cacao hunters' }, 
    { label: 'C-Amaro', value: 'c-amaro' }, 
    { label: 'Chocolate Tree, The', value: 'chocolate tree, the' }, 
    { label: 'Choklat', value: 'choklat' }, 
    { label: 'Davis', value: 'davis' }, 
    { label: 'Durci', value: 'durci' }, 
    { label: 'Emerald Estate', value: 'emerald estate' }, 
    { label: 'Frederic Blondeel', value: 'frederic blondeel' }, 
    { label: 'Georgia Ramon', value: 'georgia ramon' }, 
    { label: 'Harper Macaw', value: 'harper macaw' }, 
    { label: 'Heirloom Cacao Preservation (Millcreek)', value: 'heirloom cacao preservation (millcreek)' }, 
    { label: 'Hoja Verde (Tulicorp)', value: 'hoja verde (tulicorp)' }, 
    { label: 'Kto', value: 'kto' }, 
    { label: 'Manifesto Cacao', value: 'manifesto cacao' }, 
    { label: 'Mesocacao', value: 'mesocacao' }, 
    { label: 'Nathan Miller', value: 'nathan miller' }, 
    { label: 'Orquidea', value: 'orquidea' }, 
    { label: 'Pump Street Bakery', value: 'pump street bakery' }, 
    { label: 'Raaka', value: 'raaka' }, 
    { label: 'Sibu Sura', value: 'sibu sura' }, 
    { label: 'Sublime Origins', value: 'sublime origins' }, 
    { label: 'Taza', value: 'taza' }, 
    { label: 'Vivra', value: 'vivra' }, 
    { label: 'Zart Pralinen', value: 'zart pralinen' }, 
    { label: 'Zokoko', value: 'zokoko' }, 
    { label: 'Amano', value: 'amano' }, 
    { label: 'Bittersweet Origins', value: 'bittersweet origins' }, 
    { label: 'Blue Bandana', value: 'blue bandana' }, 
    { label: 'Bright', value: 'bright' }, 
    { label: 'Chuao Chocolatier', value: 'chuao chocolatier' }, 
    { label: 'Dole (Guittard)', value: 'dole (guittard)' }, 
    { label: 'Guido Castagna', value: 'guido castagna' }, 
    { label: 'Hogarth', value: 'hogarth' }, 
    { label: 'iQ Chocolate', value: 'iq chocolate' }, 
    { label: 'Marou', value: 'marou' }, 
    { label: 'Millcreek Cacao Roasters', value: 'millcreek cacao roasters' }, 
    { label: 'Nanea', value: 'nanea' }, 
    { label: 'Silvio Bessone', value: 'silvio bessone' }, 
    { label: 'Two Ravens', value: 'two ravens' }, 
    { label: 'Vicuna', value: 'vicuna' }, 
    { label: 'Vintage Plantations', value: 'vintage plantations' }, 
    { label: 'Brasstown aka Its Chocolate', value: 'brasstown aka its chocolate' }, 
    { label: 'Cacao Prieto', value: 'cacao prieto' }, 
    { label: 'Choco Del Sol', value: 'choco del sol' }, 
    { label: 'Chocolate Con Amor', value: 'chocolate con amor' }, 
    { label: 'Chocolate Conspiracy', value: 'chocolate conspiracy' }, 
    { label: 'Chocolate Makers', value: 'chocolate makers' }, 
    { label: 'Claudio Corallo', value: 'claudio corallo' }, 
    { label: 'Cravve', value: 'cravve' }, 
    { label: 'Daintree', value: 'daintree' }, 
    { label: 'Feitoria Cacao', value: 'feitoria cacao' }, 
    { label: 'Felchlin', value: 'felchlin' }, 
    { label: 'hexx', value: 'hexx' }, 
    { label: 'Holy Cacao', value: 'holy cacao' }, 
    { label: 'Lonohana', value: 'lonohana' }, 
    { label: 'Molucca', value: 'molucca' }, 
    { label: 'Muchomas (Mesocacao)', value: 'muchomas (mesocacao)' }, 
    { label: 'Nuance', value: 'nuance' }, 
    { label: 'Ocho', value: 'ocho' }, 
    { label: 'organicfair', value: 'organicfair' }, 
    { label: 'Palette de Bine', value: 'palette de bine' }, 
    { label: 'Parliament', value: 'parliament' }, 
    { label: 'Peppalo', value: 'peppalo' }, 
    { label: 'Sol Cacao', value: 'sol cacao' }, 
    { label: 'Solstice', value: 'solstice' }, 
    { label: 'Spagnvola', value: 'spagnvola' }, 
    { label: 'Violet Sky', value: 'violet sky' }, 
    { label: 'Bowler Man', value: 'bowler man' }, 
    { label: 'Cacao de Origin', value: 'cacao de origin' }, 
    { label: 'Cacao Store', value: 'cacao store' }, 
    { label: 'Caribeans', value: 'caribeans' }, 
    { label: 'Debauve & Gallais (Michel Cluizel)', value: 'debauve & gallais (michel cluizel)' }, 
    { label: 'Dolfin (Belcolade)', value: 'dolfin (belcolade)' }, 
    { label: 'Dormouse', value: 'dormouse' }, 
    { label: 'Just Good Chocolate', value: 'just good chocolate' }, 
    { label: 'Laia aka Chat-Noir', value: 'laia aka chat-noir' }, 
    { label: 'Machu Picchu Trading Co.', value: 'machu picchu trading co.' }, 
    { label: 'Madecasse (Cinagra)', value: 'madecasse (cinagra)' }, 
    { label: 'Mindo', value: 'mindo' }, 
    { label: 'Sacred', value: 'sacred' }, 
    { label: 'Sjolinds', value: 'sjolinds' }, 
    { label: 'Solkiki', value: 'solkiki' }, 
    { label: 'Somerville', value: 'somerville' }, 
    { label: 'Amazona', value: 'amazona' }, 
    { label: 'Franceschi', value: 'franceschi' }, 
    { label: 'Heirloom Cacao Preservation (Guittard)', value: 'heirloom cacao preservation (guittard)' }, 
    { label: 'Indaphoria', value: 'indaphoria' }, 
    { label: 'Kaoka (Cemoi)', value: 'kaoka (cemoi)' }, 
    { label: 'Kerchner', value: 'kerchner' }, 
    { label: 'L Amourette', value: 'l amourette' }, 
    { label: 'Malie Kai (Guittard)', value: 'malie kai (guittard)' }, 
    { label: 'Map Chocolate', value: 'map chocolate' }, 
    { label: 'Mars', value: 'mars' }, 
    { label: 'Menakao (aka Cinagra)', value: 'menakao (aka cinagra)' }, 
    { label: 'Neuhaus (Callebaut)', value: 'neuhaus (callebaut)' }, 
    { label: 'Obolo', value: 'obolo' }, 
    { label: 'Ohiyo', value: 'ohiyo' }, 
    { label: 'Patric', value: 'patric' }, 
    { label: 'Salgado', value: 'salgado' }, 
    { label: 'Vietcacao (A. Morin)', value: 'vietcacao (a. morin)' }, 
    { label: 'Akessons (Pralus)', value: 'akessons (pralus)' }, 
    { label: 'Askinosie', value: 'askinosie' }, 
    { label: 'Baravellis', value: 'baravellis' }, 
    { label: 'Choco Dong', value: 'choco dong' }, 
    { label: 'Chocolarder', value: 'chocolarder' }, 
    { label: 'ChocoReko', value: 'chocoreko' }, 
    { label: 'Condor', value: 'condor' }, 
    { label: 'Coppeneur', value: 'coppeneur' }, 
    { label: 'De Mendes', value: 'de mendes' }, 
    { label: 'Eau de Rose', value: 'eau de rose' }, 
    { label: 'Kyya', value: 'kyya' }, 
    { label: 'Luker', value: 'luker' }, 
    { label: 'Noir d Ebine', value: 'noir d ebine' }, 
    { label: 'Quetzalli (Wolter)', value: 'quetzalli (wolter)' }, 
    { label: 'Wellington Chocolate Factory', value: 'wellington chocolate factory' }, 
    { label: 'Xocolat', value: 'xocolat' }, 
    { label: 'Ah Cacao', value: 'ah cacao' }, 
    { label: 'French Broad', value: 'french broad' }, 
    { label: 'Glennmade', value: 'glennmade' }, 
    { label: 'Honest', value: 'honest' }, 
    { label: 'Jacque Torres', value: 'jacque torres' }, 
    { label: 'Kah Kow', value: 'kah kow' }, 
    { label: 'Marigolds Finest', value: 'marigolds finest' },
    { label: 'Blend', value: 'blend' },    
    { label: 'Dove', value: 'dove' },   
    { label: 'Green and Blacks', value: 'green and blacks' },   
    { label: 'Theo', value: 'theo' },
    { label: '? ', value: '? ' },   
];



