export const ORIGINS = [
{ label: 'Panama', value: 'panama' },
{ label: 'Ecuador', value: 'ecuador' },
{ label: 'Brazil', value: 'brazil' },
{ label: 'Bolivia', value: 'bolivia' },
{ label: 'Madagascar', value: 'madagascar' },
{ label: '', value: '' },
{ label: 'Mexico', value: 'mexico' },
{ label: 'Peru', value: 'peru' },
{ label: 'Venezuela', value: 'venezuela' },
{ label: 'Dominican Republic', value: 'dominican republic' },
{ label: 'Vietnam', value: 'vietnam' },
{ label: 'Tanzania', value: 'tanzania' },
{ label: 'Colombia', value: 'colombia' },
{ label: 'Vanuatu', value: 'vanuatu' },
{ label: 'Papua New Guinea', value: 'papua new guinea' },
{ label: 'Venezuela, Ghana', value: 'venezuela, ghana' },
{ label: 'Ven., Trinidad, Mad.', value: 'ven., trinidad, mad.' },
{ label: 'Philippines', value: 'philippines' },
{ label: 'Ecuador, Mad., PNG', value: 'ecuador, mad., png' },
{ label: 'Fiji', value: 'fiji' },
{ label: 'Gabon', value: 'gabon' },
{ label: 'Belize', value: 'belize' },
{ label: 'Indonesia', value: 'indonesia' },
{ label: 'Jamaica', value: 'jamaica' },
{ label: 'Nicaragua', value: 'nicaragua' },
{ label: 'Ghana', value: 'ghana' },
{ label: 'Carribean', value: 'carribean' },
{ label: 'Cuba', value: 'cuba' },
{ label: 'Domincan Republic', value: 'domincan republic' },
{ label: 'Solomon Islands', value: 'solomon islands' },
{ label: 'Guatemala', value: 'guatemala' },
{ label: 'Congo', value: 'congo' },
{ label: 'Grenada', value: 'grenada' },
{ label: 'Trinidad', value: 'trinidad' },
{ label: 'Haiti', value: 'haiti' },
{ label: 'Costa Rica', value: 'costa rica' },
{ label: 'Indonesia, Ghana', value: 'indonesia, ghana' },
{ label: 'Tobago', value: 'tobago' },
{ label: 'Central and S. America', value: 'central and s. america' },
{ label: 'Togo', value: 'togo' },
{ label: 'West Africa', value: 'west africa' },
{ label: 'St. Lucia', value: 'st. lucia' },
{ label: 'El Salvador', value: 'el salvador' },
{ label: 'Honduras', value: 'honduras' },
{ label: 'Hawaii', value: 'hawaii' },
{ label: 'Ven, Trinidad, Ecuador', value: 'ven, trinidad, ecuador' },
{ label: 'Gre., PNG, Haw., Haiti, Mad', value: 'gre., png, haw., haiti, mad' },
{ label: 'Sao Tome & Principe', value: 'sao tome & principe' },
{ label: 'Australia', value: 'australia' },
{ label: 'Peru(SMartin,Pangoa,nacional)', value: 'peru(smartin,pangoa,nacional)' },
{ label: 'Peru, Ecuador', value: 'peru, ecuador' },
{ label: 'Ivory Coast', value: 'ivory coast' },
{ label: 'Puerto Rico', value: 'puerto rico' },
{ label: 'Sao Tome', value: 'sao tome' },
{ label: 'Ghana, Domin. Rep', value: 'ghana, domin. rep' },
{ label: 'Dom. Rep., Madagascar', value: 'dom. rep., madagascar' },
{ label: 'Dominican Rep., Bali', value: 'dominican rep., bali' },
{ label: 'Uganda', value: 'uganda' },
{ label: 'Ven., Indonesia, Ecuad.', value: 'ven., indonesia, ecuad.' },
{ label: 'Principe', value: 'principe' },
{ label: 'Peru, Madagascar', value: 'peru, madagascar' },
{ label: 'Peru, Mad., Dom. Rep.', value: 'peru, mad., dom. rep.' },
{ label: 'Ven.,Ecu.,Peru,Nic.', value: 'ven.,ecu.,peru,nic.' },
{ label: 'Samoa', value: 'samoa' },
{ label: 'Africa, Carribean, C. Am.', value: 'africa, carribean, c. am.' },
{ label: 'Colombia, Ecuador', value: 'colombia, ecuador' },
{ label: 'Carribean(DR/Jam/Tri)', value: 'carribean(dr/jam/tri)' },
{ label: 'Venez,Africa,Brasil,Peru,Mex', value: 'venez,africa,brasil,peru,mex' },
{ label: 'Sri Lanka', value: 'sri lanka' },
{ label: 'Malaysia', value: 'malaysia' },
{ label: 'Peru, Belize', value: 'peru, belize' },
{ label: 'Ven, Bolivia, D.R.', value: 'ven, bolivia, d.r.' },
{ label: 'Peru, Ecuador, Venezuela', value: 'peru, ecuador, venezuela' },
{ label: 'Trinidad, Tobago', value: 'trinidad, tobago' },
{ label: 'Trinidad, Ecuador', value: 'trinidad, ecuador' },
{ label: 'India', value: 'india' },
{ label: 'South America, Africa', value: 'south america, africa' },
{ label: 'South America', value: 'south america' },
{ label: 'Cameroon', value: 'cameroon' },
{ label: 'Venezuela, Dom. Rep.', value: 'venezuela, dom. rep.' },
{ label: 'DR, Ecuador, Peru', value: 'dr, ecuador, peru' },
{ label: 'Ghana, Panama, Ecuador', value: 'ghana, panama, ecuador' },
{ label: 'Liberia', value: 'liberia' },
{ label: 'Trinidad-Tobago', value: 'trinidad-tobago' },
{ label: 'Venezuela/ Ghana', value: 'venezuela/ ghana' },
{ label: 'Peru, Dom. Rep', value: 'peru, dom. rep' },
{ label: 'Venezuela, Carribean', value: 'venezuela, carribean' },
{ label: 'Martinique', value: 'martinique' },
{ label: 'Mad., Java, PNG', value: 'mad., java, png' },
{ label: 'Burma', value: 'burma' },
{ label: 'Ghana & Madagascar', value: 'ghana & madagascar' },
{ label: 'Madagascar & Ecuador', value: 'madagascar & ecuador' },
{ label: 'Venezuela, Trinidad', value: 'venezuela, trinidad' },
{ label: 'Cost Rica, Ven', value: 'cost rica, ven' },
{ label: 'Nigeria', value: 'nigeria' },
{ label: 'Venezuela, Java', value: 'venezuela, java' },
{ label: 'Guat., D.R., Peru, Mad., PNG', value: 'guat., d.r., peru, mad., png' },
{ label: 'PNG, Vanuatu, Mad', value: 'png, vanuatu, mad' }
];
