export const TASTINGNOTES = [
	{ label: 'Blackberry', value: 'blackberry' }, 
    { label: 'Currant', value: 'currant' }, 
    { label: 'Blueberry', value: 'blueberry' }, 
    { label: 'Strawberry', value: 'strawberry' }, 
    { label: 'Cherry', value: 'cherry' }, 
    { label: 'Plum', value: 'plum' }, 
    { label: 'Raspberry', value: 'raspberry' }, 
    { label: 'Lemon', value: 'lemon' }, 
    { label: 'Lime', value: 'lime' }, 
    { label: 'Apple', value: 'apple' }, 
    { label: 'Melon', value: 'melon' }, 
    { label: 'Peach', value: 'peach' }, 
    { label: 'Pear', value: 'pear' }, 
    { label: 'Pineapple', value: 'pineapple' }, 
    { label: 'Almond', value: 'almond' }, 
    { label: 'Dust', value: 'dust' }, 
    { label: 'Mushroom', value: 'mushroom' }, 
    { label: 'Mint', value: 'mint' }, 
    { label: 'Black pepper', value: 'black pepper' }, 
    { label: 'Clove', value: 'clove' }, 
    { label: 'Cinnamon', value: 'cinnamon' }, 
    { label: 'Licorce', value: 'licorce' }, 
    { label: 'Rosemary', value: 'rosemary' }, 
    { label: 'Thyme', value: 'thyme' }, 
    { label: 'Vanilla', value: 'vanilla' }, 
    { label: 'Cedar', value: 'cedar' }, 
    { label: 'Tobacco', value: 'tobacco' }, 
    { label: 'Leather', value: 'leather' }, 
    { label: 'Butterscotch', value: 'butterscotch' }, 
    { label: 'Olive', value: 'olive' }, 
    { label: 'Vinegar', value: 'vinegar' }, 
    { label: 'Roasty', value: 'roasty' }, 
    { label: 'Burnt sugar', value: 'burnt sugar' }, 
    { label: 'Bread', value: 'bread' }, 
    { label: 'Toasted coconut', value: 'toasted coconut' },
    { label: 'Apricot', value: 'apricot' }, 
    { label: 'Balsamic', value: 'balsamic' }, 
    { label: 'Ripe banana', value: 'ripe banana' }, 
    { label: 'Green banana', value: 'green banana' }, 
    { label: 'Dried fruit', value: 'dried fruit' }, 
    { label: 'Molasses', value: 'molasses' }, 
    { label: 'Smoke', value: 'smoke' }, 
    { label: 'Honey', value: 'honey' },
    { label: 'Coffee', value: 'coffee' }, 
    { label: 'Toast', value: 'toast' }, 
    { label: 'Toffee', value: 'toffee' }, 
    { label: 'Milk', value: 'milk' }, 
    { label: 'Caramel', value: 'caramel' }, 
    { label: 'Grass', value: 'grass' }, 
    { label: 'Heather', value: 'heather' },
    { label: 'Gamey', value: 'gamey' }, 
    { label: 'Mold', value: 'mold' }, 
    { label: 'Fern', value: 'fern' }, 
    { label: 'Rose', value: 'rose' }, 
    { label: 'Jasmine', value: 'jasmine' }, 
    { label: 'Orange blossom', value: 'orange blossom' }, 
    { label: 'Green tea', value: 'green tea' },
    { label: 'Yeast', value: 'yeast' }, 
    { label: 'Butter', value: 'butter' }, 
    { label: 'Grape', value: 'grape' },
    { label: 'Fruity', value: 'fruity' }, 
    { label: 'Red fruit', value: 'red fruit' }, 
    { label: 'Chocolaty', value: 'chocolaty' },
    { label: 'Oak', value: 'oak' }, 
    { label: 'Alder', value: 'alder' }, 
    { label: 'Pudding', value: 'pudding' },
    { label: 'Fudge', value: 'fudge' }, 
    { label: 'Maple', value: 'maple' }
];



